# top level stuff you probably don't need to touch
# highlighter: pygments
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://saragibby.github.io
baseurl: '/'
title: saragibby
author: Sara Gibbons
description: Personal blog and resume
avatar: SaraGibbons.jpg
email: saragibby@gmail.com
github: saragibby
twitter: saragibby
linkedin: saragibby
# disqus: username
google_analytics: UA-69391421-1

gems: [jekyll-paginate]
