# Site settings
title: saragibby
email: saragibby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  some awesome description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saragibby.github.io" # the base hostname & protocol for your site
twitter_username: saragibby
github_username:  saragibby

# Build settings
markdown: kramdown
